// Package mut is the runtime linked into schemata sources generated by
// mutrim. Every mutant of a package is embedded in the rewritten code as a
// call to one of these helpers; the helper evaluates the original operation
// unless GOMUTANT_ID names its mutant.
//
// With GOMUTANT_ID unset every helper is the identity, so schemata sources
// behave exactly like the original package. The package has no
// dependencies beyond the standard library and never allocates on the hot
// path; the only cost of an inactive site is one string comparison and a
// nil check.
//
// With GOMUTANT_TRACE naming a file, every site the process reaches
// appends its ID to that file once. The runner uses it to learn which
// tests execute which mutant, so each mutant is run only against those.
package mut

import (
	"os"
	"sync"
)

// active is the mutant selected for this process, read once at init.
var active = os.Getenv("GOMUTANT_ID")

// trace receives the reached sites, or is nil when GOMUTANT_TRACE is unset.
var trace = newTracer(os.Getenv("GOMUTANT_TRACE"))

// Active reports whether the mutant id is the one selected by GOMUTANT_ID.
// Every helper calls it, so it is where reached sites are recorded.
func Active(id string) bool {
	if trace != nil {
		trace.record(id)
	}
	return active == id
}

// tracer appends each reached site ID to a file, once per process.
type tracer struct {
	mu   sync.Mutex
	seen map[string]bool
	file *os.File
}

func newTracer(path string) *tracer {
	if path == "" {
		return nil
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600) //nolint:gosec // path chosen by the runner
	if err != nil {
		panic("mut: GOMUTANT_TRACE: " + err.Error())
	}
	return &tracer{seen: map[string]bool{}, file: f}
}

func (t *tracer) record(id string) {
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.seen[id] {
		return
	}
	t.seen[id] = true
	_, _ = t.file.WriteString(id + "\n") // best effort: a lost line only widens the runner's narrowing
}

// Number is the type set on which the arithmetic helpers and Inc/Dec are
// defined: every Go numeric type, including defined types over them.
type Number interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 |
		~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr |
		~float32 | ~float64 | ~complex64 | ~complex128
}

// Integer is the subset of Number on which % is defined.
type Integer interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 |
		~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr
}

// Ordered is the type set of the comparison helper: everything < is
// defined on.
type Ordered interface {
	Integer | ~float32 | ~float64 | ~string
}

// Arith evaluates `a orig b`, or `a mutant b` when id is active. The
// operators are spelled as in Go source: "+", "-", "*", "/". Use ArithInt
// when either operator is "%".
func Arith[T Number](id string, a, b T, orig, mutant string) T {
	if Active(id) {
		orig = mutant
	}
	switch orig {
	case "+":
		return a + b
	case "-":
		return a - b
	case "*":
		return a * b
	case "/":
		return a / b
	}
	panic("mut: unsupported arithmetic operator " + orig)
}

// ArithInt is Arith for integer operands and additionally supports "%".
func ArithInt[T Integer](id string, a, b T, orig, mutant string) T {
	if Active(id) {
		orig = mutant
	}
	if orig == "%" {
		return a % b
	}
	return Arith(id, a, b, orig, orig)
}

// Cmp evaluates `a orig b`, or `a mutant b` when id is active, for the
// ordered comparison operators "<", "<=", ">", ">=".
func Cmp[T Ordered](id string, a, b T, orig, mutant string) bool {
	if Active(id) {
		orig = mutant
	}
	switch orig {
	case "<":
		return a < b
	case "<=":
		return a <= b
	case ">":
		return a > b
	case ">=":
		return a >= b
	}
	panic("mut: unsupported comparison operator " + orig)
}

// Bit evaluates `a orig b`, or `a mutant b` when id is active, for the
// bitwise operators "&", "|", "^", "&^".
func Bit[T Integer](id string, a, b T, orig, mutant string) T {
	if Active(id) {
		orig = mutant
	}
	switch orig {
	case "&":
		return a & b
	case "|":
		return a | b
	case "^":
		return a ^ b
	case "&^":
		return a &^ b
	}
	panic("mut: unsupported bitwise operator " + orig)
}

// Shift evaluates `a orig n`, or `a mutant n` when id is active, for "<<"
// and ">>". The count has its own type parameter, as in Go.
func Shift[T, S Integer](id string, a T, n S, orig, mutant string) T {
	if Active(id) {
		orig = mutant
	}
	switch orig {
	case "<<":
		return a << n
	case ">>":
		return a >> n
	}
	panic("mut: unsupported shift operator " + orig)
}

// Neg returns -x, or x when id is active.
func Neg[T Number](id string, x T) T {
	if Active(id) {
		return x
	}
	return -x
}

// Cond returns c, or forced when id is active. c is still evaluated for
// its side effects.
func Cond(id string, c, forced bool) bool {
	if Active(id) {
		return forced
	}
	return c
}

// Const returns orig, or mutant when id is active. Schemata spell a
// literal's type on orig (`mut.Const(id, int64(5), 6)`), so the mutant
// converts to it as the literal did.
func Const[T Number](id string, orig, mutant T) T {
	if Active(id) {
		return mutant
	}
	return orig
}

// Not returns c, or !c when id is active. It lowers condition negation and
// the == <-> != swap, which is exactly a negation for every Go type.
func Not(id string, c bool) bool {
	if Active(id) {
		return !c
	}
	return c
}

// And evaluates `a && b()`, or `a || b()` when id is active. b is a
// closure so that short-circuit evaluation is preserved.
func And(id string, a bool, b func() bool) bool {
	if Active(id) {
		return a || b()
	}
	return a && b()
}

// Or evaluates `a || b()`, or `a && b()` when id is active.
func Or(id string, a bool, b func() bool) bool {
	if Active(id) {
		return a && b()
	}
	return a || b()
}

// Inc performs *p++, or *p-- when id is active.
func Inc[T Number](id string, p *T) {
	if Active(id) {
		*p--
	} else {
		*p++
	}
}

// Dec performs *p--, or *p++ when id is active.
func Dec[T Number](id string, p *T) {
	if Active(id) {
		*p++
	} else {
		*p--
	}
}
