// Package mut is the runtime linked into schemata sources generated by
// mutrim. Every mutant of a package is embedded in the rewritten code as a
// call to one of these helpers; the helper evaluates the original operation
// unless GOMUTANT_ID names its mutant.
//
// With GOMUTANT_ID unset every helper is the identity, so schemata sources
// behave exactly like the original package. The package has no
// dependencies beyond the standard library and never allocates on the hot
// path; the only cost of an inactive site is one string comparison.
package mut

import "os"

// active is the mutant selected for this process, read once at init.
var active = os.Getenv("GOMUTANT_ID")

// Active reports whether the mutant id is the one selected by GOMUTANT_ID.
func Active(id string) bool { return active == id }

// Number is the type set on which the arithmetic helpers and Inc/Dec are
// defined: every Go numeric type, including defined types over them.
type Number interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 |
		~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr |
		~float32 | ~float64 | ~complex64 | ~complex128
}

// Integer is the subset of Number on which % is defined.
type Integer interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 |
		~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr
}

// Ordered is the type set of the comparison helper: everything < is
// defined on.
type Ordered interface {
	Integer | ~float32 | ~float64 | ~string
}

// Arith evaluates `a orig b`, or `a mutant b` when id is active. The
// operators are spelled as in Go source: "+", "-", "*", "/". Use ArithInt
// when either operator is "%".
func Arith[T Number](id string, a, b T, orig, mutant string) T {
	if Active(id) {
		orig = mutant
	}
	switch orig {
	case "+":
		return a + b
	case "-":
		return a - b
	case "*":
		return a * b
	case "/":
		return a / b
	}
	panic("mut: unsupported arithmetic operator " + orig)
}

// ArithInt is Arith for integer operands and additionally supports "%".
func ArithInt[T Integer](id string, a, b T, orig, mutant string) T {
	if Active(id) {
		orig = mutant
	}
	if orig == "%" {
		return a % b
	}
	return Arith(id, a, b, orig, orig)
}

// Cmp evaluates `a orig b`, or `a mutant b` when id is active, for the
// ordered comparison operators "<", "<=", ">", ">=".
func Cmp[T Ordered](id string, a, b T, orig, mutant string) bool {
	if Active(id) {
		orig = mutant
	}
	switch orig {
	case "<":
		return a < b
	case "<=":
		return a <= b
	case ">":
		return a > b
	case ">=":
		return a >= b
	}
	panic("mut: unsupported comparison operator " + orig)
}

// Not returns c, or !c when id is active. It lowers condition negation and
// the == <-> != swap, which is exactly a negation for every Go type.
func Not(id string, c bool) bool {
	if Active(id) {
		return !c
	}
	return c
}

// And evaluates `a && b()`, or `a || b()` when id is active. b is a
// closure so that short-circuit evaluation is preserved.
func And(id string, a bool, b func() bool) bool {
	if Active(id) {
		return a || b()
	}
	return a && b()
}

// Or evaluates `a || b()`, or `a && b()` when id is active.
func Or(id string, a bool, b func() bool) bool {
	if Active(id) {
		return a && b()
	}
	return a || b()
}

// Inc performs *p++, or *p-- when id is active.
func Inc[T Number](id string, p *T) {
	if Active(id) {
		*p--
	} else {
		*p++
	}
}

// Dec performs *p--, or *p++ when id is active.
func Dec[T Number](id string, p *T) {
	if Active(id) {
		*p++
	} else {
		*p--
	}
}
