package mutator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/ast/astutil"
	"golang.org/x/tools/go/packages"
)

// RuntimePath is the import path of the runtime package that schemata
// sources call into.
const RuntimePath = "github.com/illumination-k/mutrim/mut"

// schemataHeader marks generated files so a later gen run excludes them.
const schemataHeader = "// Code generated by mutrim (schemata); DO NOT EDIT.\n\n"

// Lowering is what a Site.Schemata callback may use to build its
// replacement node.
type Lowering struct {
	// Cursor positions the site's node in the file being rewritten. Its
	// children may already have been lowered for inner sites.
	Cursor *astutil.Cursor
	// ID is the mutant being embedded.
	ID string

	runtime string // import name of RuntimePath in this file
}

// Call builds `mut.fn(id, args...)`.
func (l *Lowering) Call(fn string, args ...ast.Expr) *ast.CallExpr {
	return &ast.CallExpr{
		Fun:  &ast.SelectorExpr{X: ast.NewIdent(l.runtime), Sel: ast.NewIdent(fn)},
		Args: append([]ast.Expr{l.idLit()}, args...),
	}
}

// Active builds `mut.Active(id)`.
func (l *Lowering) Active() ast.Expr { return l.Call("Active") }

func (l *Lowering) idLit() ast.Expr {
	return &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(l.ID)}
}

// Schemata is the outcome of Lower: rewritten sources with every embedded
// mutant selectable at runtime through GOMUTANT_ID.
type Schemata struct {
	// Files maps each rewritten file's original path to its new contents.
	// Files without an embedded mutant are absent and used as they are.
	Files map[string][]byte
	// Embedded holds the IDs of the mutants present in Files. Viable
	// mutants that are missing here cannot be expressed as schemata (see
	// the operator docs) and must not be executed.
	Embedded map[string]bool
}

// Lower rewrites pkg so that every viable, non-ignored mutant in mutants
// is embedded and selected by GOMUTANT_ID. The package's syntax trees are
// rewritten in place and must not be reused afterwards.
func Lower(pkg *packages.Package, mutants []Mutant) (*Schemata, error) {
	out := &Schemata{Files: map[string][]byte{}, Embedded: map[string]bool{}}
	if pkg.PkgPath == RuntimePath {
		return out, nil // the runtime cannot import itself
	}

	byNode := map[ast.Node][]Mutant{}
	byFile := map[*ast.File][]Mutant{}
	for _, m := range mutants {
		if m.Ignored != "" || !m.Viable || m.site.Schemata == nil {
			continue
		}
		byNode[m.site.Node] = append(byNode[m.site.Node], m)
		byFile[m.site.file] = append(byFile[m.site.file], m)
	}
	for _, ms := range byNode {
		// Expression rewrites first, then the operators that wrap the result.
		sort.SliceStable(ms, func(i, j int) bool {
			return !wraps(ms[i].Operator) && wraps(ms[j].Operator)
		})
	}

	for _, f := range pkg.Syntax {
		if len(byFile[f]) == 0 {
			continue
		}
		name := pkg.Fset.Position(f.Package).Filename
		runtime := runtimeName(pkg, f)
		astutil.Apply(f, nil, func(c *astutil.Cursor) bool {
			for _, m := range byNode[c.Node()] {
				l := &Lowering{Cursor: c, ID: m.ID, runtime: runtime}
				if n := m.site.Schemata(l); n != nil {
					c.Replace(n)
					out.Embedded[m.ID] = true
				}
			}
			return true
		})
		// runtimeName never reuses a name the file already binds, so the
		// import is always added (a second import of RuntimePath under a
		// new name when the package already uses the runtime).
		astutil.AddNamedImport(pkg.Fset, f, runtime, RuntimePath)
		keepDirectives(f)

		var buf bytes.Buffer
		buf.WriteString(schemataHeader)
		if err := format.Node(&buf, pkg.Fset, f); err != nil {
			return nil, fmt.Errorf("mutator: format schemata for %s: %w", name, err)
		}
		out.Files[name] = buf.Bytes()
	}
	return out, nil
}

// wraps reports whether the operator's schemata wrap the node's current
// lowering (read at lowering time) instead of rebuilding it from the
// original node's parts.
func wraps(operator string) bool {
	return operator == Negation{}.Name() || operator == Condition{}.Name()
}

// runtimeName picks an import name for the runtime that no identifier in f
// or in the package scope uses.
func runtimeName(pkg *packages.Package, f *ast.File) string {
	used := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok {
			used[id.Name] = true
		}
		return true
	})
	name := "mut"
	for i := 1; used[name] || pkg.Types.Scope().Lookup(name) != nil; i++ {
		name = "mut" + strconv.Itoa(i)
	}
	return name
}

// keepDirectives drops every comment group without a //go: directive
// (build constraints, embed, noinline). Rewritten bodies have no
// positions the printer could place ordinary comments against, and
// dropping them keeps the output valid; directives keep their meaning
// because declarations are printed where they were.
func keepDirectives(f *ast.File) {
	kept := []*ast.CommentGroup{}
	for _, g := range f.Comments {
		for _, c := range g.List {
			if strings.HasPrefix(c.Text, "//go:") {
				kept = append(kept, g)
				break
			}
		}
	}
	f.Comments = kept
}

// boolClosure builds `func() bool { return e }`.
func boolClosure(e ast.Expr) *ast.FuncLit {
	return &ast.FuncLit{
		Type: &ast.FuncType{
			Params:  &ast.FieldList{},
			Results: &ast.FieldList{List: []*ast.Field{{Type: ast.NewIdent("bool")}}},
		},
		Body: &ast.BlockStmt{List: []ast.Stmt{&ast.ReturnStmt{Results: []ast.Expr{e}}}},
	}
}

func opLit(t token.Token) ast.Expr {
	return &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(t.String())}
}
