package mutator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/ast/astutil"
	"golang.org/x/tools/go/packages"
)

// RuntimePath is the import path of the runtime package that schemata
// sources call into by default: package mut of mutrim, which the target
// module must then depend on. A driver that injects a copy of the runtime
// (mut.Source) into the build passes that copy's import path to Lower.
const RuntimePath = "github.com/illumination-k/mutrim/mut"

// schemataHeader marks generated files so a later gen run excludes them.
const schemataHeader = "// Code generated by mutrim (schemata); DO NOT EDIT.\n\n"

// Lowering is what a Site.Schemata callback may use to build its
// replacement node.
type Lowering struct {
	// Cursor positions the site's node in the file being rewritten. Its
	// children may already have been lowered for inner sites.
	Cursor *astutil.Cursor
	// ID is the mutant being embedded.
	ID string

	runtime string   // import name of the runtime in this file
	current ast.Node // the node's lowering so far
}

// Current is the node the site sits on, as the lowerings of the mutants
// embedded before it left it. A site whose replacement embeds the node must
// read it from here, not from the original node, so that the mutants of one
// node nest instead of replacing each other.
func (l *Lowering) Current() ast.Node { return l.current }

// Stmt and Expr are Current for the two kinds of node a site replaces.
func (l *Lowering) Stmt() ast.Stmt { return l.current.(ast.Stmt) }

func (l *Lowering) Expr() ast.Expr { return l.current.(ast.Expr) }

// Call builds `mut.fn(id, args...)`.
func (l *Lowering) Call(fn string, args ...ast.Expr) *ast.CallExpr {
	return &ast.CallExpr{
		Fun:  &ast.SelectorExpr{X: ast.NewIdent(l.runtime), Sel: ast.NewIdent(fn)},
		Args: append([]ast.Expr{l.idLit()}, args...),
	}
}

// Active builds `mut.Active(id)`.
func (l *Lowering) Active() ast.Expr { return l.Call("Active") }

func (l *Lowering) idLit() ast.Expr {
	return &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(l.ID)}
}

// Schemata is the outcome of Lower: rewritten sources with every embedded
// mutant selectable at runtime through GOMUTANT_ID.
type Schemata struct {
	// Files maps each rewritten file's original path to its new contents.
	// Files without an embedded mutant are absent and used as they are.
	Files map[string][]byte
	// Embedded holds the IDs of the mutants present in Files. Viable,
	// non-excluded mutants that are missing here cannot be expressed as
	// schemata (see the operator docs) and must not be executed.
	Embedded map[string]bool
}

// Lower rewrites pkg so that every viable mutant in mutants that is not Excluded
// is embedded and selected by GOMUTANT_ID, and every block in blocks (see
// Blocks) records itself through mut.Reach. The rewritten files import the
// runtime from runtimePath, RuntimePath or an injected copy of it. The
// package's syntax trees are rewritten in place and must not be reused
// afterwards.
func Lower(pkg *packages.Package, mutants []Mutant, blocks []Block, runtimePath string) (*Schemata, error) {
	out := &Schemata{Files: map[string][]byte{}, Embedded: map[string]bool{}}
	if pkg.PkgPath == runtimePath {
		return out, nil // the runtime cannot import itself
	}

	byNode := map[ast.Node][]Mutant{}
	lowered := map[*ast.File]bool{} // the files to rewrite
	for _, m := range mutants {
		if m.Excluded() || !m.Viable || m.site.Schemata == nil {
			continue
		}
		byNode[m.site.Node] = append(byNode[m.site.Node], m)
		lowered[m.site.file] = true
	}
	blockAt := map[ast.Node]string{}
	for _, b := range blocks {
		blockAt[b.node] = b.ID
		lowered[b.file] = true
	}
	for _, ms := range byNode {
		// The rewrite that rebuilds the node first, then the ones that wrap
		// what it left.
		sort.SliceStable(ms, func(i, j int) bool {
			return !ms[i].site.Wraps && ms[j].site.Wraps
		})
	}

	for _, f := range pkg.Syntax {
		if !lowered[f] {
			continue
		}
		name := pkg.Fset.Position(f.Package).Filename
		runtime := runtimeName(pkg, f)
		astutil.Apply(f, nil, func(c *astutil.Cursor) bool {
			current := c.Node()
			lowered := false
			for _, m := range byNode[c.Node()] {
				if lowered && !m.site.Wraps {
					continue // its replacement would discard the lowering before it
				}
				l := &Lowering{Cursor: c, ID: m.ID, runtime: runtime, current: current}
				if n := m.site.Schemata(l); n != nil {
					c.Replace(n)
					current = n
					lowered = true
					out.Embedded[m.ID] = true
				}
			}
			// The block is entered even when a mutant embedded above
			// skips its statements, so Reach goes ahead of them.
			if id, ok := blockAt[c.Node()]; ok {
				(&Lowering{ID: id, runtime: runtime}).reach(current)
			}
			return true
		})
		// runtimeName never reuses a name the file already binds, so the
		// import is always added (a second import of the runtime under a
		// new name when the package already uses it).
		astutil.AddNamedImport(pkg.Fset, f, runtime, runtimePath)
		keepDirectives(f)

		var buf bytes.Buffer
		buf.WriteString(schemataHeader)
		if err := format.Node(&buf, pkg.Fset, f); err != nil {
			return nil, fmt.Errorf("mutator: format schemata for %s: %w", name, err)
		}
		out.Files[name] = buf.Bytes()
	}
	return out, nil
}

// runtimeName picks an import name for the runtime that no identifier in f
// or in the package scope uses.
func runtimeName(pkg *packages.Package, f *ast.File) string {
	used := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok {
			used[id.Name] = true
		}
		return true
	})
	name := "mut"
	for i := 1; used[name] || pkg.Types.Scope().Lookup(name) != nil; i++ {
		name = "mut" + strconv.Itoa(i)
	}
	return name
}

// keepDirectives drops every comment group without a //go: directive
// (build constraints, embed, noinline). Rewritten bodies have no
// positions the printer could place ordinary comments against, and
// dropping them keeps the output valid; directives keep their meaning
// because declarations are printed where they were.
func keepDirectives(f *ast.File) {
	kept := []*ast.CommentGroup{}
	for _, g := range f.Comments {
		for _, c := range g.List {
			if strings.HasPrefix(c.Text, "//go:") {
				kept = append(kept, g)
				break
			}
		}
	}
	f.Comments = kept
}

// boolClosure builds `func() bool { return e }`.
func boolClosure(e ast.Expr) *ast.FuncLit {
	return &ast.FuncLit{
		Type: &ast.FuncType{
			Params:  &ast.FieldList{},
			Results: &ast.FieldList{List: []*ast.Field{{Type: ast.NewIdent("bool")}}},
		},
		Body: &ast.BlockStmt{List: []ast.Stmt{&ast.ReturnStmt{Results: []ast.Expr{e}}}},
	}
}

func opLit(t token.Token) ast.Expr {
	return &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(t.String())}
}
