load("@buildifier_prebuilt//:rules.bzl", "buildifier")

# Development-only targets; consumers of the module never load this package.

buildifier(
    name = "buildifier",
    exclude_patterns = ["./bazel-*/*"],
    lint_mode = "fix",
    mode = "fix",
)

buildifier(
    name = "buildifier.check",
    exclude_patterns = ["./bazel-*/*"],
    lint_mode = "warn",
    mode = "diff",
)
