load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "runner",
    srcs = [
        "diff.go",
        "exec.go",
        "hash.go",
        "report.go",
        "runner.go",
    ],
    importpath = "github.com/illumination-k/mutrim/runner",
    visibility = ["//visibility:public"],
    deps = [
        "//mutator",
        "@org_golang_x_sync//errgroup",
    ],
)
